name: Build and Release Gridfinity STLs

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # Matches version tags like v1.0.0

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t gridfinity-builder .

      - name: Create dist directory
        run: mkdir -p dist

      - name: Run variables.py to generate STL files into dist/
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace gridfinity-builder \
            sh -c "cd /workspace && python3 builder/variables.py bins.yaml && mv *.stl dist/ || true"

      - name: Push STL files to dist/
        env:
          GIT_AUTHOR_NAME: Micah Fitzgerald
          GIT_AUTHOR_EMAIL: mcfitz2@gmail.com
          PUSH_PAT: ${{ secrets.PUSH_PAT }}
        run: |
          git config --global user.name "$GIT_AUTHOR_NAME"
          git config --global user.email "$GIT_AUTHOR_EMAIL"
          git remote set-url origin https://x-access-token:${PUSH_PAT}@github.com/${{ github.repository }}.git
          git add dist/*.stl
          git commit -m "Add generated STL files to dist [skip ci]" || echo "No changes to commit"
          git push